#define DARK_BLUE 1    //À¶É«
#define DARK_GREEN 2   //ÉîÂÌ
#define BLUE 3         //À¶
#define RED 4          //ºì
#define PURPLE 5       //×Ï
#define BROWN 6        //×Ø
#define GREY 7         //»Ò
#define BLACK 8        //ºÚ
#define CYAN 9         //Çà
#define GREEN 10       //ÂÌ
#define LIGHT_BLUE 11  //Ç³À¶
#define ORANGE 12      //³È
#define PINK 13        //·Û
#define YELLOW 14      //»Æ
#define WHITE 15       //°×